### ISSUE TITLE
请问，运行app.py文件出现ValueError: too many values to unpack (expected 7)，怎么解决呢

### ISSUE THREAD

**Issue by Gangaself** [luxuantao/car_knowledge_graph#2]
![image](https://user-images.githubusercontent.com/35550974/171987440-3e107d81-93eb-40ce-9fb0-4ff0e0399dd1.png)

实在是不知道错误出现在了哪里？

**Comment by ShellandCore** [comment]
我也遇到了相同的问题，请问您解决了吗？

**Comment by ShellandCore** [comment]
问题找到啦，把py2neo的版本升级到2020.1.1就可以了
